apiVersion: apps/v1
kind: Deployment
metadata:
  name: banka
  labels:
    name: banka
    app: banka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banka
  template:
    metadata:
      name: banka
      labels:
        app: banka
        name: banka
    spec:
      restartPolicy: Always
      containers:
        - name: banka
          image: corda/corda-zulu-java1.8-4.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 10201, 10200, 2222


---

apiVersion: v1
kind: Service
metadata:
  name: banka
  labels:
    app: banka
    name: banka
spec:
  type: NodePort
  ports:
    - nodePort: 31222
      port: 2222
      targetPort: 2222
  selector:
    app: banka
    name: banka

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: banka-config-pv-volume
  labels:
    type: local
    app: banka
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/naoufal/corda_kubernetes/BankA/config"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: banka-config-pv-claim
  labels:
    app: banka
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: banka-certificates-pv-volume
  labels:
    type: local
    app: banka
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/naoufal/corda_kubernetes/BankA/certificates"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: banka-certificates-pv-claim
  labels:
    app: banka
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: banka-persistence-pv-volume
  labels:
    type: local
    app: banka
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/naoufal/corda_kubernetes/BankA/persistence"
    type: DirectoryOrCreate

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: banka-persistence-pv-claim
  labels:
    app: banka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: banka-logs-pv-volume
  labels:
    type: local
    app: banka
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/naoufal/corda_kubernetes/BankA/logs"
    type: DirectoryOrCreate

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: banka-logs-pv-claim
  labels:
    app: banka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cordapp-pv-volume
  labels:
    type: local
    app: banka
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/naoufal/corda_kubernetes/shared/cordapps"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cordapp-pv-claim
  labels:
    app: banka
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: node-infos-pv-volume
  labels:
    type: local
    app: banka
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/naoufal/corda_kubernetes/shared/node-infos"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-infos-pv-claim
  labels:
    app: banka
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: network-parameters-pv-volume
  labels:
    type: local
    app: banka
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/naoufal/corda_kubernetes/shared/network-parameters"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: network-parameters-pv-claim
  labels:
    app: banka
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi