apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    name: keycloak
spec:
  type: NodePort
  ports:
    #    - name: http
    #      protocol: TCP
    #      port: 8080
    #      nodePort: 30080
    - name: http
      nodePort: 30080
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
    name: keycloak

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    name: keycloak
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
        name: keycloak
    spec:
      restartPolicy: Always
      containers:
        - name: keycloak
          image: jboss/keycloak
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          env:
            - name: KEYCLOAK_LOGLEVEL
              value: "DEBUG"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_ADDR
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "project"
          volumeMounts:
            - mountPath: /tmp/realm.json
              name: keycloak-imported-conf
      volumes:
        - name: keycloak-imported-conf
          persistentVolumeClaim:
            claimName: keycloak-pv-claim

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: keycloak-pv-volume
  labels:
    type: local
    app: keycloak
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/c/dev/bank-operations-backend/keycloak/realm.json"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-pv-claim
  labels:
    app: keycloak
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi