#apiVersion: apps/v1beta1
#kind: StatefulSet
#metadata:
#  name: rabbitmq
#spec:
#  replicas: 1
#  serviceName: rabbitmq
#  selector:
#    matchLabels:
#      app: rabbitmq
#  template:
#    metadata:
#      labels:
#        app: rabbitmq
#    spec:
#      containers:
#        - name: rabbitmq
#          image: rabbitmq:3-management
#          imagePullPolicy: "IfNotPresent"
#          volumeMounts:
#            - mountPath: /var/lib/rabbitmq
#              name: rabbitmq-data
#      volumes:
#        - name: rabbitmq-data
#          hostPath:
#            path: /data/rabbitmq
#            type: DirectoryOrCreate

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5672
          resources:
            limits:
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq